# Generated by Django 5.2.2 on 2025-06-15 20:17

from django.db import migrations

def populate_status(apps, schemaeditor):
    entries = {
        "to_do": "This issue is yet to be started.",
        "in_progress": "This issue is currently being worked on.",
        "done": "This issue has been completed.",
    }
    Status = apps.get_model('issues', 'Status')
    for key, value in entries.items():
        status_obj = Status(name=key, description=value)
        status_obj.save()

class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_status)
    ]