# Generated by Django 5.2.2 on 2025-06-10 20:35

from django.db import migrations

def populate_role(apps, schemaeditor):
    entries = {
        "developer": "Responsible for working on issues",
        "product owner": "The person who defines issues",
        "scrum master": "The team's coach",
    }
    Role = apps.get_model('accounts', 'Role')
    for key, value in entries.items():
        role_obj = Role(name=key, description=value)
        role_obj.save()

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_role)
    ]
