# Generated by Django 5.2.2 on 2025-06-10 20:36

from django.db import migrations

def populate_team(apps, schemaeditor):
    entries = {
        "alpha": "The backend team, responsible for the API and database",
        "bravo": "The frontend team, responsible for the user interface",
        "charlie": "The mobile apps team, responsible for iOS and Android applications",
    }
    Team = apps.get_model('accounts', 'Team')
    for key, value in entries.items():
        team_obj = Team(name=key, description=value)
        team_obj.save()

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20250610_2035'),
    ]

    operations = [
        migrations.RunPython(populate_team)
    ]
